"""remove message_count

Revision ID: 37444d708acb
Revises: 8626d74bfe2e
Create Date: 2026-03-16 12:50:03.336247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37444d708acb'
down_revision: Union[str, Sequence[str], None] = '8626d74bfe2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_summaries', 'message_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_summaries', sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
